export const projects = [
  {
    title: 'Big Green Dildo NFT',
    description: "Using React, Solidity and the power of WalletConnect, I built the NFT Mint DApp for the Big Green Dildo collection that randomly mints one of the NFTs in the 10,000 NFT collection to the user. The NFT Dapp is deployed on the Ethereum mainnet",
    image: '/images/bgd-project.jpg',
    tags: ['Solidity', 'React', 'WalletConnect', 'Ethers.js'],
    source: 'https://github.com/Akay74/NFT-mint-DApp',
    visit: 'https://nft.biggreendildo.org',
    id: 0,
  },
  {
    title: 'KombatBets',
    description:"Kombat Bets is an online crypto betting game where users stake USDT on mortal kombat characters. The rounds for the game are played by 12pm daily and users who win or draw automatically receive the earnings in their wallets. The contract is deployed to the Binance Smart Chain and is automated using Chainlink features.",
    image: '/images/kb-media.png',
    tags: ['VueJS', 'JavaScript', 'Chainlink', 'Moralis', 'Solidity'],
    source: 'https://github.com/Akay74/kombat-bets-contract',
    visit: 'https://kombatbets.io',
    id: 1,
  },
  {
    title: 'Spotlx',
    description: "The Spotlx app is a Laundry Management System that helps users book their laundry service, have it picked up, cleaned and delivered back to them. It features real time tracking of user orders from Pick up to Delivery.",
    image: '/images/spotlx-media.jpg',
    tags: ['React Native', 'NestJS', 'Express', 'Firebase'],
    source: 'https://Ttechan.io/spotlx',
    visit: 'https://spotlx.techan.io',
    id: 2,
  },
  {
    title: 'Zinar NFT',
    description: "This is a suite of contracts for the Zinari Finance Zinar NFT. The contracts are able to mint NFTs, set referrals earnings for NFTs, and stake NFTs for ERC20 tokens",
    image: '/images/zinari-media.jpg',
    tags: ['React', 'Solidity', 'Alchemy', 'Metamask'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Yuan DAO',
    description: "This is a lean version of the Openzeppelin Governance contracts, built to suit the simpler needs of the Yuan token ecosystem",
    image: '/images/zinari-media.jpg',
    tags: ['React', 'Solidity', 'Alchemy', 'Metamask'],
    source: 'https://governance.yuantoken.io',
    visit: 'https://github.com/Akay74/Yuan-DAO',
    id: 4,
  },
];
