export const projects = [
  {
    title: 'Big Green Dildo NFT',
    description: "Using React, Solidity and the power of WalletConnect, I built the NFT Mint DApp for the Big Green Dildo collection that randomly mints one of the NFTs in the 10,000 NFT collection to the user. The NFT Dapp is deployed on the Ethereum mainnet",
    image: '/images/bgd-project.jpg',
    tags: ['Solidity', 'React', 'WalletConnect', 'Ethers.js'],
    source: 'https://github.com/Akay74/NFT-mint-DApp',
    visit: 'https://nft.biggreendildo.org',
    id: 0,
  },
  {
    title: 'Placeholder',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Placeholder',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Placeholder',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];
